apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-real-world
spec:
  selector:
    matchLabels:
      app: hello-real-world
  template:
    metadata:
      labels:
        app: hello-real-world
    spec:
      containers:
      - name: hello-real-world
        image: realworld.azurecr.io/hello-world:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
